import { Injectable, Logger } from '@nestjs/common';
import { ClassType } from '@sheetOdm/types/query.types';
import { MetadataRegistry } from '@sheetOdm/services/metadata-registry.service';
import { SheetDataGateway } from '@sheetOdm/gateway/sheetDataGateway';
import { IdGenerator } from '@sheetOdm/core/utils/idgenerator';


@Injectable()
export class EntityInterceptor {
    private readonly logger = new Logger(EntityInterceptor.name);

    constructor(private readonly metadataRegistry: MetadataRegistry) { }

    public async applyAutogeneratedFields<T extends object>(
        entityClass: ClassType<T>,
        gateway: SheetDataGateway,
        entity: any,
        sheetName: string
    ): Promise<void> {
        const columns = this.metadataRegistry.getColumnDetails(entityClass);

        for (const [key, config] of Object.entries(columns)) {
            if (!config || (!config.generated && !config.isAutoIncrement)) continue;

            if (!entity[key]) {
                if (config.generated === 'uuid') {
                    entity[key] = IdGenerator.generate();
                } else if (config.generated === 'short-id') {
                    entity[key] = IdGenerator.generateShort();
                } else if (config.isAutoIncrement || config.generated === 'increment') {
                    entity[key] = await this.calculateAutoIncrement(entityClass, gateway, sheetName, key);
                }
            }
        }
    }

    private async calculateAutoIncrement<T extends object>(
        entityClass: ClassType<T>,
        gateway: SheetDataGateway,
        sheetName: string,
        propertyKey: string
    ): Promise<number> {
        try {
            // Obtenemos el mapa de columnas para saber en qué índice (A, B, C...) está el ID
            const columnMap = this.metadataRegistry.getColumnMap(entityClass);
            const physicalColIndex = columnMap[propertyKey];

            // Convertimos el índice numérico a letra (Ej: 0 -> A, 2 -> C)
            const colLetter = this.indexToColumnLetter(physicalColIndex);

            // 🚀 Súper optimización: Solo descargamos LA COLUMNA del ID, no toda la tabla
            const columnData = await gateway.getRange(`${sheetName}!${colLetter}2:${colLetter}`);

            let maxId = 0;
            for (const row of columnData) {
                const val = parseInt(row[0], 10);
                if (!isNaN(val) && val > maxId) maxId = val;
            }
            return maxId + 1;
        } catch (e) {
            this.logger.warn(`Fallback AutoIncrement en ${sheetName}: ${e.message}`);
            return 1;
        }
    }

    private indexToColumnLetter(index: number): string {
        let temp = index;
        let letter = '';
        while (temp >= 0) {
            letter = String.fromCharCode((temp % 26) + 65) + letter;
            temp = Math.floor(temp / 26) - 1;
        }
        return letter;
    }

    public sanitizeDeleteControl<T extends object>(entityClass: ClassType<T>, entity: any): void {
        const deleteControlProp = this.metadataRegistry.getDeleteControlProperty(entityClass);
        if (deleteControlProp && entity[deleteControlProp] === undefined) {
            entity[deleteControlProp] = false;
        }
    }
}